In [1]:
import numpy as np

In [2]:
class RNN:
    def __init__(self, Wx, Wh, b):
        self.params = [Wx, Wh, b]
        self.grads = [np.zeros_like(Wx), np.zeros_like(Wh), np.zeros_like(b)]
        self.cache = None

    def forward(self, x, h_prev):
        Wx, Wh, b = self.params
        t = np.dot(h_prev, Wh) + np.dot(x, Wx) + b
        h_next = np.tanh(t)

        self.cache = (x, h_prev, h_next)
        return h_next

    def backward(self, dh_next):
        Wx, Wh, b = self.params
        x, h_prev, h_next = self.cache

        dt = dh_next * (1 - h_next ** 2)
        db = np.sum(dt, axis=0)
        dWh = np.dot(h_prev.T, dt)
        dh_prev = np.dot(dt, Wh.T)
        dWx = np.dot(x.T, dt)
        dx = np.dot(dt, Wx.T)

        self.grads[0][...] = dWx
        self.grads[1][...] = dWh
        self.grads[2][...] = db

        return dx, dh_prev

In [3]:
# N: バッチサイズ
# H: 隠れ層次元
# D: データ次元
N, H, D = 5, 3, 2
Wh = np.ones((H, H));
Wx = np.ones((D, H));
b = np.ones((N, H));
hp = np.zeros((N, H));
x = np.arange(N * D).reshape((N, D));
print(x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [4]:
rnn = RNN(Wx, Wh, b)

In [5]:
dh_next = rnn.forward(x, hp)
print(dh_next, dh_next.shape)

[[0.96402758 0.96402758 0.96402758]
 [0.99998771 0.99998771 0.99998771]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]] (5, 3)


In [6]:
dx, dh_prev = rnn.backward(dh_next)
np.set_printoptions(precision=4)

In [7]:
dx

array([[2.0433e-01, 2.0433e-01],
       [7.3729e-05, 7.3729e-05],
       [2.4734e-08, 2.4734e-08],
       [8.2974e-12, 8.2974e-12],
       [2.6645e-15, 2.6645e-15]])

In [8]:
dh_prev

array([[2.0433e-01, 2.0433e-01, 2.0433e-01],
       [7.3729e-05, 7.3729e-05, 7.3729e-05],
       [2.4734e-08, 2.4734e-08, 2.4734e-08],
       [8.2974e-12, 8.2974e-12, 8.2974e-12],
       [2.6645e-15, 2.6645e-15, 2.6645e-15]])

In [9]:
rnn.grads[0]

array([[4.9185e-05, 4.9185e-05, 4.9185e-05],
       [6.8183e-02, 6.8183e-02, 6.8183e-02]])

In [10]:
rnn.grads[1]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
rnn.grads[2]

array([[0.0681, 0.0681, 0.0681],
       [0.0681, 0.0681, 0.0681],
       [0.0681, 0.0681, 0.0681],
       [0.0681, 0.0681, 0.0681],
       [0.0681, 0.0681, 0.0681]])